name: Auto Update Jobs from Telegram

on:
  schedule:
    - cron: "0 */6 * * *"   # har 6 ghante
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libraries
        run: |
          pip install telethon requests beautifulsoup4

      - name: Run Telegram Job Bot
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
        run: |
          python telegram_bot.py

      - name: Commit & Push Updates
        run: |
          git config --global user.name "job-bot"
          git config --global user.email "bot@github.com"
          git add jobs.json
          git commit -m "Auto update jobs" || echo "No changes"
          git push
